<?xml version="1.0" encoding="utf-8"?><Database Name="Sportblog" Class="DBClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-OTPO2DA\SQLEXPRESS;Initial Catalog=Sportblog;Integrated Security=True" SettingsObjectName="Sportblog.Properties.Settings" SettingsPropertyName="SportblogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.categorys" Member="categories">
    <Type Name="category">
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="category_post" Member="posts" ThisKey="category_id" OtherKey="category_id" Type="post" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="reg_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_comment" Member="comments" ThisKey="user_id" OtherKey="user_id" Type="comment" />
      <Association Name="user_post" Member="posts" ThisKey="user_id" OtherKey="user_id" Type="post" />
      <Association Name="user_user_info" Member="user_infos" ThisKey="user_id" OtherKey="user_id" Type="user_info" />
      <Association Name="role_user" Member="role" ThisKey="role_id" OtherKey="role_id" Type="role" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId1">
      <Argument Parameter="username" Member="username" />
      <Argument Parameter="email" Member="email" />
      <Argument Parameter="pass" Member="password" />
      <Argument Parameter="role_id" Member="role_id" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.comments" Member="comments">
    <Type Name="comment">
      <Column Name="comment_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="comment_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="post_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_comment" Member="user" ThisKey="user_id" OtherKey="user_id" Type="user" IsForeignKey="true" />
      <Association Name="post_comment" Member="post" ThisKey="post_id" OtherKey="post_id" Type="post" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dictionary" Member="dictionaries">
    <Type Name="dictionary">
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.posts" Member="posts">
    <Type Name="post">
      <Column Name="post_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="post_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="post_comment" Member="comments" ThisKey="post_id" OtherKey="post_id" Type="comment" />
      <Association Name="category_post" Member="category" ThisKey="category_id" OtherKey="category_id" Type="category" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="user_post" Member="user" ThisKey="user_id" OtherKey="user_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="role_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="role_user" Member="users" ThisKey="role_id" OtherKey="role_id" Type="user" />
    </Type>
  </Table>
  <Table Name="dbo.user_infos" Member="user_infos">
    <Type Name="user_info">
      <Column Name="info_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sex" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="about" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_user_info" Member="user" ThisKey="user_id" OtherKey="user_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteUser" Method="DeleteUser">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateUsers" Method="UpdateUsers">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pass" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="r_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId1" Name="dbo.InsertUsers" Method="InsertUsers">
    <Parameter Name="username" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pass" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="role_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>